version: '3.8'

services:
  app:
    container_name: chatfusion-dev
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: builder  # Stop at builder stage for dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules  # Prevent overwriting node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
