version: '3.8'

services:
  app:
    container_name: chatfusion
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app  # Optional: for live development
    command: npm run dev
